### ISSUE TITLE
Большое спасибо.

### ISSUE THREAD

**Issue by Dims-M** [0xLaileb/IniFile#1]
Хочу выразит благодарность и большое человеческое спасибо за  класс IniFile.
Очень помог. Надеюсь будет радовать многих разрабов. Которым не придётся пилить смой велосипеды.
 Спасибо за классный способ(класс) работы с ini файлом на C#/

**Comment by 0xLaileb** [comment]
Инструмент заброшен, но спасибо за отзыв 😘

🤔 Он подходит для простой работы с ini-файлами на Windows, но я думаю вы можете найти лучше библиотеки для работы с ini-файлами на NuGet, например:
https://www.nuget.org/packages/ini-parser/#usedby-body-tab
GitHub: https://github.com/rickyah/ini-parser
